language: node_js

node_js:
  - "7"

before_install:
  - npm i -g npm@5

install:
  - npm ci

script:
  - npm run lint
  - npm run build
  - export SEQ_SILENT=true
  - npm run cover

after_success:
 - 'nyc report --reporter=lcov > coverage.lcov && codecov'
