language: node_js

node_js:
  - "6.1"

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run cover

after_success:
 - 'nyc report --reporter=lcov > coverage.lcov && codecov'
