# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: 'Node.js Package'

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Cache dependencies'
        uses: 'actions/cache@v2'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - uses: 'actions/setup-node@v2.1.4'
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org/'

      - run: 'npm install'
      - run: 'npm run build'
      - run: 'npm publish'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
